name: C Test Suite

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      total_score: 100

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: apt updates & installs
      run: sudo apt-get update && sudo apt-get install -y build-essential

    - name: Test Fonction nb 1
      run: |
        gcc -o test -Wall -Wextra -Werror -std=c99 -pedantic -Wvla test.c >> compiling.txt
        if [ $(./fonksiyon | grep "10 + 2 = 12" | wc -l) -eq 1 ]; then echo "Toplama fonksiyonu testi geçti."; else echo "Toplama fonksiyonu testi başarısız oldu."; fi
        echo "${GITHUB_ACTOR} Toplama Fonksiyonu: 25" >> not.txt

    - name: results
      run: |
        total_score=0
        while read -r line; do
          score=$(echo "$line" | awk '{print $NF}')
          total_score=$((total_score + score))
        done < not.txt
        export total_score
        echo "${GITHUB_ACTOR} puanınız: $total_score" >> not.txt
    - name: upload compile
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-compile
        path: compiling.txt 

    - name: upload results
      uses: actions/upload-artifact@v4
      with:
        name: test-suite
        path: not.txt
